//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DesktopAssistant.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.10.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Clipboard_1 {
            get {
                return ((string)(this["Clipboard_1"]));
            }
            set {
                this["Clipboard_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Clipboard_2 {
            get {
                return ((string)(this["Clipboard_2"]));
            }
            set {
                this["Clipboard_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Clipboard_3 {
            get {
                return ((string)(this["Clipboard_3"]));
            }
            set {
                this["Clipboard_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Clipboard_4 {
            get {
                return ((string)(this["Clipboard_4"]));
            }
            set {
                this["Clipboard_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Clipboard_5 {
            get {
                return ((string)(this["Clipboard_5"]));
            }
            set {
                this["Clipboard_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tasklist_1 {
            get {
                return ((string)(this["Tasklist_1"]));
            }
            set {
                this["Tasklist_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tasklist_2 {
            get {
                return ((string)(this["Tasklist_2"]));
            }
            set {
                this["Tasklist_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tasklist_3 {
            get {
                return ((string)(this["Tasklist_3"]));
            }
            set {
                this["Tasklist_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tasklist_4 {
            get {
                return ((string)(this["Tasklist_4"]));
            }
            set {
                this["Tasklist_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Tasklist_5 {
            get {
                return ((string)(this["Tasklist_5"]));
            }
            set {
                this["Tasklist_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Tasklist_1_isEnabled {
            get {
                return ((bool)(this["Tasklist_1_isEnabled"]));
            }
            set {
                this["Tasklist_1_isEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Tasklist_2_isEnabled {
            get {
                return ((bool)(this["Tasklist_2_isEnabled"]));
            }
            set {
                this["Tasklist_2_isEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Tasklist_3_isEnabled {
            get {
                return ((bool)(this["Tasklist_3_isEnabled"]));
            }
            set {
                this["Tasklist_3_isEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Tasklist_4_isEnabled {
            get {
                return ((bool)(this["Tasklist_4_isEnabled"]));
            }
            set {
                this["Tasklist_4_isEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Tasklist_5_isEnabled {
            get {
                return ((bool)(this["Tasklist_5_isEnabled"]));
            }
            set {
                this["Tasklist_5_isEnabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.Collections.Generic.List<DesktopAssistant.TaskListNotification> ListOfNotifications {
            get {
                return ((global::System.Collections.Generic.List<DesktopAssistant.TaskListNotification>)(this["ListOfNotifications"]));
            }
            set {
                this["ListOfNotifications"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FilesByTaskbars_InString {
            get {
                return ((string)(this["FilesByTaskbars_InString"]));
            }
            set {
                this["FilesByTaskbars_InString"] = value;
            }
        }
    }
}
